'use client';
import { useEffect, useRef, useState } from 'react';
import { Icon } from './icons';

function loadScript(src, globalName) { return new Promise((resolve,reject)=>{ if(window[globalName]) return resolve(window[globalName]); const s=document.createElement('script'); s.src=src; s.async=true; s.onload=()=>resolve(window[globalName]); s.onerror=()=>reject(new Error(`Could not load ${src}`)); document.head.appendChild(s); }); }

export default function Scan({ onBack, onScanned, onDemo }) {
  const videoRef=useRef(null), canvasRef=useRef(null), streamRef=useRef(null), frameRef=useRef(null), scanningRef=useRef(false); const [running,setRunning]=useState(false); const [status,setStatus]=useState('Point the camera at an EduPay QR code'); const fileRef=useRef(null);
  useEffect(()=>()=>stop(),[]);
  const stop=()=>{scanningRef.current=false; if(frameRef.current) cancelAnimationFrame(frameRef.current); if(streamRef.current){streamRef.current.getTracks().forEach(t=>t.stop());streamRef.current=null;} setRunning(false);};
  const tick=async()=>{ if(!scanningRef.current) return; const video=videoRef.current, canvas=canvasRef.current; if(video?.readyState===video.HAVE_ENOUGH_DATA){canvas.width=video.videoWidth;canvas.height=video.videoHeight;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(video,0,0,canvas.width,canvas.height);try{const jsQR=window.jsQR;if(jsQR){const data=ctx.getImageData(0,0,canvas.width,canvas.height);const code=jsQR(data.data,data.width,data.height,{inversionAttempts:'dontInvert'});if(code?.data){handle(code.data);return;}}}catch{}} frameRef.current=requestAnimationFrame(tick); };
  const start=async()=>{ try{await loadScript('https://cdnjs.cloudflare.com/ajax/libs/jsqr/1.4.0/jsQR.min.js','jsQR'); const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});streamRef.current=stream;videoRef.current.srcObject=stream;await videoRef.current.play();scanningRef.current=true;setRunning(true);setStatus('Scanning…');tick();}catch(e){setStatus(`Camera unavailable: ${e.message}`);onDemo?.('Camera permission or HTTPS may be required.');} };
  const handle=(text)=>{stop(); if(navigator.vibrate)navigator.vibrate(100);let payload=null;try{payload=JSON.parse(text)}catch{} if(payload?.app==='edupay-demo')onScanned({name:payload.name||'Merchant',upiId:payload.upiId||'unknown@edu',amount:Number(payload.amount||0)});else onScanned({name:'Scanned QR',upiId:text.slice(0,40),amount:0});};
  const file=async(e)=>{const f=e.target.files?.[0];if(!f)return;try{await loadScript('https://cdnjs.cloudflare.com/ajax/libs/jsqr/1.4.0/jsQR.min.js','jsQR');const img=new Image();img.onload=()=>{const c=canvasRef.current;c.width=img.width;c.height=img.height;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,0,0);const d=ctx.getImageData(0,0,c.width,c.height);const code=window.jsQR?.(d.data,d.width,d.height,{inversionAttempts:'attemptBoth'});if(code?.data)handle(code.data);else setStatus('No QR code found in that image.');};img.src=URL.createObjectURL(f);}catch{setStatus('Could not read that image.');}};
  return <section className="screen active scan-screen"><header className="scan-topbar"><button onClick={()=>{stop();onBack();}} aria-label="Back"><Icon name="arrowLeft"/></button><div><strong>Scan &amp; Pay</strong><small>Scan a QR to continue</small></div><button onClick={()=>onDemo('Scan help')} aria-label="Help"><Icon name="help"/></button></header><div className="scanner-shell"><div className="scanner-area"><video ref={videoRef} playsInline muted/><canvas ref={canvasRef} hidden/><div className="scanner-dim"/><div className={`scan-frame ${running?'active':''}`}><i/><i/><i/><i/><span/></div>{!running&&<div className="scanner-idle"><div className="scanner-qr-mark"><Icon name="qr" size={60}/></div><strong>Scan any EduPay QR</strong><span>Allow camera access and place the QR inside the frame</span></div>}<div className="scanner-actions"><button className="scan-primary" onClick={running?stop:start}>{running?<><Icon name="x" size={18}/> Stop Camera</>:<><Icon name="camera" size={18}/> Start Camera</>}</button><button className="scan-secondary" onClick={()=>fileRef.current?.click()}><Icon name="upload" size={18}/> Upload QR</button><input ref={fileRef} onChange={file} type="file" accept="image/*" capture="environment" hidden/></div></div><div className="scan-control-row"><button onClick={()=>onDemo('Flip camera')}><Icon name="refresh"/><small>Flip</small></button><button onClick={()=>onDemo('Flash control is device dependent')}><Icon name="flash"/><small>Flash</small></button><button onClick={stop}><Icon name="x"/><small>Stop</small></button></div></div><div className="status-bar"><span className="status-dot"/>{status}</div><div className="scan-note">For this classroom demo, scanning a generated EduPay QR opens the payment confirmation screen.</div></section>;
}
