'use client';
import { useState } from 'react';
import { Icon } from './icons';
import { formatINR } from '../lib/storage';

export function SendScreen({ onBack, onContinue }) { const [name,setName]=useState(''); const [upi,setUpi]=useState(''); const [amount,setAmount]=useState(''); return <section className="screen active"><SimpleHeader title="Send to UPI ID" onBack={onBack}/><div className="form-card"><label>Payee name</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Campus Canteen"/><label>UPI ID</label><input value={upi} onChange={e=>setUpi(e.target.value)} placeholder="e.g. canteen@edu"/><label>Amount</label><input type="number" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="e.g. 100" inputMode="numeric"/><button className="primary-btn" onClick={()=>onContinue({name,upiId:upi,amount:Number(amount)})}>Continue</button></div></section> }
export function ReceiveScreen({ profile, onBack, onDemo }) { const [amount,setAmount]=useState(''); const [qr,setQr]=useState(''); const generate=()=>{ const payload=JSON.stringify({app:'edupay-demo',name:profile.name,upiId:profile.upiId, ...(amount?{amount:Number(amount)}:{})}); setQr(payload); window.setTimeout(()=>{const node=document.getElementById('react-qrcode'); if(node && window.QRCode){node.innerHTML=''; new window.QRCode(node,{text:payload,width:220,height:220,colorDark:'#111',colorLight:'#fff'});} },0);}; return <section className="screen active"><SimpleHeader title="Receive Money" onBack={onBack}/><div className="form-card"><label>Amount to request (optional)</label><input type="number" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="e.g. 50"/><button className="primary-btn" onClick={generate}>Generate QR Code</button></div>{qr&&<div className="qr-display"><div id="react-qrcode"/><div className="qr-caption">{amount?`Requesting ${formatINR(amount)} to ${profile.upiId}`:`Receive to ${profile.upiId} (any amount)`}</div><div className="demo-tag">Show this QR to another EduPay demo device.</div></div>} </section> }
export function ConfirmScreen({ txn, balance, onBack, onConfirm }) { const [amount,setAmount]=useState(String(txn?.amount||'')); return <section className="screen active"><SimpleHeader title="Confirm Payment" onBack={onBack}/><div className="confirm-card"><div className="payee-avatar">{txn?.name?.[0]?.toUpperCase()||'?'}</div><div className="payee-name">{txn?.name}</div><div className="payee-upi">{txn?.upiId}</div><div className="amount-input-wrap"><span>₹</span><input type="number" value={amount} onChange={e=>setAmount(e.target.value)}/></div><div className="balance-hint">Available demo balance: {formatINR(balance)}</div><button className="primary-btn" onClick={()=>onConfirm(Number(amount))}>Pay Now</button></div></section> }
export function PinScreen({ onBack, onComplete }) { const [pin,setPin]=useState(''); return <section className="screen active"><SimpleHeader title="Enter UPI PIN" onBack={onBack}/><div className="pin-area"><div className="pin-hint">Demo PIN pad — enter any 4 digits</div><div className="pin-dots">{[0,1,2,3].map(i=><span key={i} className={i<pin.length?'filled':''}/>)}</div><div className="pin-pad">{['1','2','3','4','5','6','7','8','9','⌫','0','✓'].map(key=><button key={key} onClick={()=>key==='⌫'?setPin(p=>p.slice(0,-1)):key==='✓'?onComplete(pin):pin.length<4&&setPin(p=>p+key)}>{key}</button>)}</div></div></section> }
function SimpleHeader({title,onBack}) { return <header className="top-bar"><button className="icon-btn" onClick={onBack} aria-label="Back"><Icon name="arrowLeft"/></button><div className="title">{title}</div><div style={{width:40}}/></header> }
