'use client';
import { useState } from 'react';
import { Icon } from './icons';
import { formatINR } from '../lib/storage';

export default function Transaction({ entry, onBack, onSendAgain, onHistory, onDemo }) {
  const [details, setDetails] = useState(true);
  const date = new Date(entry.time);
  const utr = entry.txnId ? entry.txnId.replace(/^DEMO/, '4268') + '116' : '-';
  return <section className="screen transaction-screen active"><header className="transaction-topbar"><button onClick={onBack} aria-label="Back"><Icon name="arrowLeft" size={28}/></button><div><div>Transaction Successful</div><small>{date.toLocaleString('en-IN', {hour:'2-digit', minute:'2-digit', day:'2-digit', month:'short', year:'numeric'})}</small></div><button onClick={()=>onDemo('Transaction options')} aria-label="More"><Icon name="more" size={25}/></button></header><div className="transaction-scroll"><div className="success-banner"><div className="success-check-ring"><Icon name="check" size={40} strokeWidth={3}/></div><div className="success-title">Payment Successful</div><div className="success-time">{date.toLocaleString('en-IN', {day:'2-digit', month:'short', year:'numeric', hour:'2-digit', minute:'2-digit'})}</div></div><div className="paid-card"><div className="paid-card-label">Paid to</div><div className="payee-summary"><div className="payee-logo">{entry.name?.[0]?.toUpperCase() || 'U'}</div><div className="payee-summary-main"><div className="payee-summary-name">{entry.name}</div><div className="payee-summary-upi">{entry.upiId}</div></div><div className="payee-summary-amount">{formatINR(entry.amount)}</div></div><div className="banking-name-row"><span>Banking Name</span><strong>{entry.name?.toUpperCase()}</strong><span className="verified-dot">✓</span></div><div className="payment-details-head"><span>▣</span> Payment Details <button onClick={()=>setDetails(v=>!v)} aria-label="Toggle details">{details?'⌃':'⌄'}</button></div>{details && <div className="payment-details-body"><Detail label="Transaction ID" value={entry.txnId} copy onDemo={onDemo}/><Detail label="Debited from" value="XXXXXX4144"/><Detail label="Amount" value={formatINR(entry.amount)}/><Detail label="UTR" value={utr} copy onDemo={onDemo}/></div>}<div className="transaction-actions"><Action label="Send Again" icon="send" onClick={onSendAgain}/><Action label="View History" icon="clock" onClick={onHistory}/><Action label="Split Expense" icon="plus" onClick={()=>onDemo('Split Expense')}/><Action label="Share Receipt" icon="upload" onClick={()=>{ if(navigator.share) navigator.share({title:'EduPay Receipt',text:`EduPay payment: ${formatINR(entry.amount)} to ${entry.name}`}).catch(()=>{}); else onDemo('Receipt sharing'); }}/></div></div><button className="support-row" onClick={()=>onDemo('EduPay Support')}><span>?</span><div>Contact EduPay Support</div><b>›</b></button><div className="powered-demo">Powered by <strong>EduPay</strong> • UPI DEMO</div><div className="demo-tag transaction-demo-tag">Simulated transaction for classroom teaching only</div></div><div className="transaction-bottom"><button onClick={onBack}>DONE</button></div></section>;
}
function Detail({label,value,copy,onDemo}) { return <div className="detail-row"><span>{label}</span><strong>{value}</strong>{copy?<button onClick={()=>navigator.clipboard?.writeText(value).then(()=>onDemo('Copied to clipboard')).catch(()=>onDemo(value))} aria-label={`Copy ${label}`}><Icon name="copy" size={16}/></button>:<span/>}</div> }
function Action({label,icon,onClick}) { return <button onClick={onClick}><span><Icon name={icon} size={17}/></span><small>{label}</small></button> }
